### ISSUE TITLE
Better styling of the manual composition component

### ISSUE THREAD

**Issue by dbluhm** [decentralized-identity/didcomm-demo#44]

**Comment by dbluhm** [comment]
CSS borrowed from my recent work on https://dbluhm.github.io/did-peer-4-ts/:

```css
lit-code {
	--editor-bg-color:      #f5f2f0;
	--hl-color-string:      #690;
	--hl-color-function:    #004eff;
	--hl-color-number:      #dd9031;
	--hl-color-operator:    #9a6e3a;
	--hl-color-class-name:  #78c3ca;
	--hl-color-punctuation: #999;
	--hl-color-property:    #905;
	--hl-color-keyword:     #8500ff;
	--hl-color-comment:     #aaa;
}
```
